Repository thoughtbot/administrate, pull requests merged in 2020-10, with the labels that each got.

#1357 Add word-break to attribute-data
  app/assets/stylesheets/administrate/components/_attributes.scss
Labels: feature, views-and-styles

#1064 human_attribute_name instead of raw attr_name
  app/controllers/administrate/application_controller.rb
  app/views/administrate/application/_collection.html.erb
  app/views/administrate/application/show.html.erb
Labels: bug, i18n

#1063 number_field for Field::Number
  app/views/fields/number/_form.html.erb
Labels: feature, fields

#1226 Fix Time fields bug which occurs when Time value is nil
  app/views/fields/time/_index.html.erb
  app/views/fields/time/_show.html.erb
  spec/administrate/views/fields/time/_index_spec.rb
Labels: bug, fields

#1259 Use Show Page Attributes When Rendering a has_one Relationship On Another Record's Show Page
  app/views/fields/has_one/_show.html.erb
  lib/administrate/field/has_one.rb
  spec/administrate/views/fields/has_one/_show_spec.rb
  spec/lib/fields/has_one_spec.rb
Labels: feature, models

#1222 Include_blank in Belongs to form
  app/views/fields/belongs_to/_form.html.erb
  docs/customizing_dashboards.md
  lib/administrate/field/belongs_to.rb
  spec/example_app/app/dashboards/customer_dashboard.rb
  spec/features/form_spec.rb
  spec/lib/fields/belongs_to_spec.rb
Labels: feature, fields

#1404 UUID's should be rendered Field::String
  lib/generators/administrate/dashboard/dashboard_generator.rb
Labels: bug, fields

#991 Find routes config
  lib/administrate/generator_helpers.rb
  lib/generators/administrate/install/install_generator.rb
  lib/generators/administrate/routes/routes_generator.rb
  spec/lib/administrate/generator_helpers_spec.rb
Labels: feature, install

#1626 Allow translating resource names in CRUD messages
  lib/administrate/resource_resolver.rb
  spec/features/edit_page_spec.rb
  spec/features/log_entries_form_spec.rb
  spec/features/log_entries_index_spec.rb
  spec/lib/administrate/resource_resolver_spec.rb
Labels: feature, i18n

#1630 Add CSP tags to default layout
  app/views/layouts/administrate/application.html.erb
Labels: feature, views-and-styles

#1548 Test against Ruby 2.7 on CircleCI
  .circleci/config.yml
Labels: dependencies, maintenance

#1602 Update Ruby version
  .ruby-version
Labels: dependencies

#1633 Automatic associations
  docs/customizing_dashboards.md
  lib/administrate.rb
  lib/administrate/base_dashboard.rb
  lib/administrate/field/associative.rb
  lib/administrate/field/belongs_to.rb
  lib/administrate/field/deferred.rb
  lib/administrate/field/has_many.rb
  lib/administrate/field/has_one.rb
  lib/administrate/field/polymorphic.rb
  lib/administrate/search.rb
  lib/generators/administrate/dashboard/dashboard_generator.rb
  spec/dashboards/order_dashboard_spec.rb
  spec/example_app/app/dashboards/customer_dashboard.rb
  spec/generators/dashboard_generator_spec.rb
  spec/lib/administrate/search_spec.rb
  spec/lib/fields/belongs_to_spec.rb
  spec/lib/fields/boolean_spec.rb
  spec/lib/fields/deferred_spec.rb
  spec/lib/fields/has_many_spec.rb
  spec/lib/fields/has_one_spec.rb
  spec/lib/fields/number_spec.rb
  spec/lib/fields/password_spec.rb
  spec/lib/fields/polymorphic_spec.rb
  spec/lib/fields/string_spec.rb
  spec/support/field_matchers.rb
Labels: feature, models

#1804 Enable Selectize for polymorphic fields
  app/assets/javascripts/administrate/components/associative.js
  app/assets/stylesheets/administrate/components/_field-unit.scss
Labels: feature, fields

#1813 Document both demo apps consistently
  CONTRIBUTING.md
  README.md
  administrate.gemspec
Labels: bug, documentation

#1782 Adding an error message during 'administrate' initialize when there are no models in db.
  lib/generators/administrate/install/install_generator.rb
Labels: feature, install
