Repository thoughtbot/administrate, pull requests merged in 2020-01, with the labels that each got.

#1514 Rewrite the contributing guide
  CONTRIBUTING.md
  README.md
  docs/contributing.md
  spec/example_app/app/views/layouts/docs.html.erb
Labels: documentation

#1187 Update comment with new Administrate namespace
  lib/generators/administrate/install/templates/application_controller.rb.erb
Labels: bug, documentation

#1376 Add a "back" link to the navigation
  app/assets/stylesheets/administrate/components/_buttons.scss
  app/assets/stylesheets/administrate/components/_navigation.scss
  app/views/administrate/application/_navigation.html.erb
  spec/features/navigation_spec.rb
Labels: feature, views-and-styles

#1531 Remove project level rubocop.yml
  .rubocop.yml
Labels: dependencies, maintenance
