Repository thoughtbot/administrate, pull requests merged in 2020-06, with the labels that each got.

#1655 Detect enum fields as Selects rather than as Strings
  lib/administrate/field/select.rb
  lib/generators/administrate/dashboard/dashboard_generator.rb
  spec/generators/dashboard_generator_spec.rb
Labels: feature, fields

#1667 Update Appraisal Capybara from 3.31.1 to 3.32.2
  gemfiles/rails42.gemfile
  gemfiles/rails50.gemfile
  gemfiles/rails51.gemfile
  gemfiles/rails52.gemfile
  gemfiles/rails60.gemfile
Labels: dependencies

#1591 Check if routes can be shown in navigation
  app/helpers/administrate/application_helper.rb
  app/views/administrate/application/_navigation.html.erb
  spec/example_app/app/controllers/admin/application_controller.rb
  spec/example_app/app/policies/blog/post_policy.rb
  spec/example_app/app/policies/customer_policy.rb
  spec/example_app/app/policies/line_item_policy.rb
  spec/example_app/app/policies/log_entry_policy.rb
  spec/example_app/app/policies/payment_policy.rb
  spec/example_app/app/policies/series_policy.rb
  spec/example_app/app/policies/stats_policy.rb
  spec/features/authorization_spec.rb
Labels: dashboards, security

#1687 `protected` visibility is discouraged
  lib/administrate/field/associative.rb
  lib/administrate/field/polymorphic.rb
  lib/administrate/page/base.rb
  lib/administrate/page/form.rb
Labels: maintenance
