Repository thoughtbot/administrate, pull requests merged in 2020-03, with the labels that each got.

#1398 Support association search for other types of association fields
  lib/administrate/search.rb
Labels: feature, search

#1165 Change Albanian two-letter code to "sq" as per ISO 639-1
  config/locales/administrate.sq.yml
Labels: bug, i18n

#1589 Dynamic select field
  docs/customizing_dashboards.md
  lib/administrate/field/select.rb
  spec/example_app/app/dashboards/product_dashboard.rb
  spec/example_app/app/models/product.rb
  spec/example_app/db/migrate/20200326202615_add_release_year_to_products.rb
  spec/example_app/db/schema.rb
  spec/factories.rb
  spec/features/products_form_spec.rb
  spec/models/product_spec.rb
Labels: feature, fields
