Repository thoughtbot/administrate, pull requests merged in 2020-05, with the labels that each got.

#1618 Remove jquery ujs
  app/assets/javascripts/administrate/application.js
  spec/example_app/app/assets/javascripts/application.js
Labels: dependencies, views-and-styles

#1620 Remove unused variables in scss files
  app/assets/stylesheets/administrate/components/_flashes.scss
  app/assets/stylesheets/administrate/library/_variables.scss
Labels: views-and-styles

#1648 Recursively process nested parameters for polymorphism
  app/controllers/administrate/application_controller.rb
  spec/controllers/admin/log_entries_controller_spec.rb
Labels: bug, dashboards, models
